INSERT INTO UnitType (UnitTypeID, UnitTypeName, CityDistState, Hierarchy, Active) VALUES (1, 'Police Station', 'City', 3, true);
INSERT INTO UnitType (UnitTypeID, UnitTypeName, CityDistState, Hierarchy, Active) VALUES (2, 'District HQ', 'District', 2, true);

INSERT INTO Unit (UnitID, UnitName, TypeID, ParentUnit, NationalityID, StateID, DistrictID, Active) VALUES (1, 'Bengaluru Urban District HQ', 2, NULL, 1, 1, 1, true);
INSERT INTO Unit (UnitID, UnitName, TypeID, ParentUnit, NationalityID, StateID, DistrictID, Active) VALUES (2, 'Koramangala PS', 1, 1, 1, 1, 1, true);
INSERT INTO Unit (UnitID, UnitName, TypeID, ParentUnit, NationalityID, StateID, DistrictID, Active) VALUES (3, 'HSR Layout PS', 1, 1, 1, 1, 1, true);
INSERT INTO Unit (UnitID, UnitName, TypeID, ParentUnit, NationalityID, StateID, DistrictID, Active) VALUES (4, 'Whitefield PS', 1, 1, 1, 1, 1, true);
INSERT INTO Unit (UnitID, UnitName, TypeID, ParentUnit, NationalityID, StateID, DistrictID, Active) VALUES (5, 'Indiranagar PS', 1, 1, 1, 1, 1, true);
INSERT INTO Unit (UnitID, UnitName, TypeID, ParentUnit, NationalityID, StateID, DistrictID, Active) VALUES (6, 'Rajajinagar PS', 1, 1, 1, 1, 1, true);
INSERT INTO Unit (UnitID, UnitName, TypeID, ParentUnit, NationalityID, StateID, DistrictID, Active) VALUES (7, 'Mysuru District HQ', 2, NULL, 1, 1, 2, true);
INSERT INTO Unit (UnitID, UnitName, TypeID, ParentUnit, NationalityID, StateID, DistrictID, Active) VALUES (8, 'Mysuru City PS', 1, 7, 1, 1, 2, true);
INSERT INTO Unit (UnitID, UnitName, TypeID, ParentUnit, NationalityID, StateID, DistrictID, Active) VALUES (9, 'Nazarbad PS', 1, 7, 1, 1, 2, true);
INSERT INTO Unit (UnitID, UnitName, TypeID, ParentUnit, NationalityID, StateID, DistrictID, Active) VALUES (10, 'Jayalakshmipuram PS', 1, 7, 1, 1, 2, true);
INSERT INTO Unit (UnitID, UnitName, TypeID, ParentUnit, NationalityID, StateID, DistrictID, Active) VALUES (11, 'Tumakuru District HQ', 2, NULL, 1, 1, 3, true);
INSERT INTO Unit (UnitID, UnitName, TypeID, ParentUnit, NationalityID, StateID, DistrictID, Active) VALUES (12, 'Tumakuru City PS', 1, 11, 1, 1, 3, true);
INSERT INTO Unit (UnitID, UnitName, TypeID, ParentUnit, NationalityID, StateID, DistrictID, Active) VALUES (13, 'Tiptur PS', 1, 11, 1, 1, 3, true);
INSERT INTO Unit (UnitID, UnitName, TypeID, ParentUnit, NationalityID, StateID, DistrictID, Active) VALUES (14, 'Belagavi District HQ', 2, NULL, 1, 1, 4, true);
INSERT INTO Unit (UnitID, UnitName, TypeID, ParentUnit, NationalityID, StateID, DistrictID, Active) VALUES (15, 'Belagavi City PS', 1, 14, 1, 1, 4, true);
INSERT INTO Unit (UnitID, UnitName, TypeID, ParentUnit, NationalityID, StateID, DistrictID, Active) VALUES (16, 'Gokak PS', 1, 14, 1, 1, 4, true);
INSERT INTO Unit (UnitID, UnitName, TypeID, ParentUnit, NationalityID, StateID, DistrictID, Active) VALUES (17, 'Kalaburagi District HQ', 2, NULL, 1, 1, 5, true);
INSERT INTO Unit (UnitID, UnitName, TypeID, ParentUnit, NationalityID, StateID, DistrictID, Active) VALUES (18, 'Kalaburagi City PS', 1, 17, 1, 1, 5, true);
INSERT INTO Unit (UnitID, UnitName, TypeID, ParentUnit, NationalityID, StateID, DistrictID, Active) VALUES (19, 'Aland PS', 1, 17, 1, 1, 5, true);
INSERT INTO Unit (UnitID, UnitName, TypeID, ParentUnit, NationalityID, StateID, DistrictID, Active) VALUES (20, 'Dakshina Kannada District HQ', 2, NULL, 1, 1, 6, true);
INSERT INTO Unit (UnitID, UnitName, TypeID, ParentUnit, NationalityID, StateID, DistrictID, Active) VALUES (21, 'Mangaluru City PS', 1, 20, 1, 1, 6, true);
INSERT INTO Unit (UnitID, UnitName, TypeID, ParentUnit, NationalityID, StateID, DistrictID, Active) VALUES (22, 'Ullal PS', 1, 20, 1, 1, 6, true);
INSERT INTO Unit (UnitID, UnitName, TypeID, ParentUnit, NationalityID, StateID, DistrictID, Active) VALUES (23, 'Dharwad District HQ', 2, NULL, 1, 1, 7, true);
INSERT INTO Unit (UnitID, UnitName, TypeID, ParentUnit, NationalityID, StateID, DistrictID, Active) VALUES (24, 'Hubballi City PS', 1, 23, 1, 1, 7, true);
INSERT INTO Unit (UnitID, UnitName, TypeID, ParentUnit, NationalityID, StateID, DistrictID, Active) VALUES (25, 'Dharwad Rural PS', 1, 23, 1, 1, 7, true);
INSERT INTO Unit (UnitID, UnitName, TypeID, ParentUnit, NationalityID, StateID, DistrictID, Active) VALUES (26, 'Ballari District HQ', 2, NULL, 1, 1, 8, true);
INSERT INTO Unit (UnitID, UnitName, TypeID, ParentUnit, NationalityID, StateID, DistrictID, Active) VALUES (27, 'Ballari City PS', 1, 26, 1, 1, 8, true);
INSERT INTO Unit (UnitID, UnitName, TypeID, ParentUnit, NationalityID, StateID, DistrictID, Active) VALUES (28, 'Sandur PS', 1, 26, 1, 1, 8, true);
INSERT INTO Unit (UnitID, UnitName, TypeID, ParentUnit, NationalityID, StateID, DistrictID, Active) VALUES (29, 'Shivamogga District HQ', 2, NULL, 1, 1, 9, true);
INSERT INTO Unit (UnitID, UnitName, TypeID, ParentUnit, NationalityID, StateID, DistrictID, Active) VALUES (30, 'Shivamogga City PS', 1, 29, 1, 1, 9, true);
INSERT INTO Unit (UnitID, UnitName, TypeID, ParentUnit, NationalityID, StateID, DistrictID, Active) VALUES (31, 'Sagar PS', 1, 29, 1, 1, 9, true);
INSERT INTO Unit (UnitID, UnitName, TypeID, ParentUnit, NationalityID, StateID, DistrictID, Active) VALUES (32, 'Hassan District HQ', 2, NULL, 1, 1, 10, true);
INSERT INTO Unit (UnitID, UnitName, TypeID, ParentUnit, NationalityID, StateID, DistrictID, Active) VALUES (33, 'Hassan City PS', 1, 32, 1, 1, 10, true);
INSERT INTO Unit (UnitID, UnitName, TypeID, ParentUnit, NationalityID, StateID, DistrictID, Active) VALUES (34, 'Belur PS', 1, 32, 1, 1, 10, true);
