INSERT INTO Act (ActCode, ActDescription, ShortName, Active) VALUES ('IPC', 'Indian Penal Code', 'IPC', true);
INSERT INTO Act (ActCode, ActDescription, ShortName, Active) VALUES ('NDPS', 'Narcotic Drugs and Psychotropic Substances Act', 'NDPS', true);
INSERT INTO Act (ActCode, ActDescription, ShortName, Active) VALUES ('ITACT', 'Information Technology Act', 'ITACT', true);
INSERT INTO Act (ActCode, ActDescription, ShortName, Active) VALUES ('POCSO', 'Protection of Children from Sexual Offences Act', 'POCSO', true);
INSERT INTO Act (ActCode, ActDescription, ShortName, Active) VALUES ('CUSTOMS', 'Customs Act', 'CUSTOMS', true);
INSERT INTO Act (ActCode, ActDescription, ShortName, Active) VALUES ('DVACT', 'Protection of Women from Domestic Violence Act', 'DVACT', true);

INSERT INTO Section (ActCode, SectionCode, SectionDescription, Active) VALUES ('IPC', '379', 'IPC Section 379', true);
INSERT INTO Section (ActCode, SectionCode, SectionDescription, Active) VALUES ('IPC', '380', 'IPC Section 380', true);
INSERT INTO Section (ActCode, SectionCode, SectionDescription, Active) VALUES ('IPC', '457', 'IPC Section 457', true);
INSERT INTO Section (ActCode, SectionCode, SectionDescription, Active) VALUES ('IPC', '392', 'IPC Section 392', true);
INSERT INTO Section (ActCode, SectionCode, SectionDescription, Active) VALUES ('IPC', '393', 'IPC Section 393', true);
INSERT INTO Section (ActCode, SectionCode, SectionDescription, Active) VALUES ('IPC', '411', 'IPC Section 411', true);
INSERT INTO Section (ActCode, SectionCode, SectionDescription, Active) VALUES ('IPC', '356', 'IPC Section 356', true);
INSERT INTO Section (ActCode, SectionCode, SectionDescription, Active) VALUES ('IPC', '323', 'IPC Section 323', true);
INSERT INTO Section (ActCode, SectionCode, SectionDescription, Active) VALUES ('IPC', '324', 'IPC Section 324', true);
INSERT INTO Section (ActCode, SectionCode, SectionDescription, Active) VALUES ('IPC', '302', 'IPC Section 302', true);
INSERT INTO Section (ActCode, SectionCode, SectionDescription, Active) VALUES ('IPC', '307', 'IPC Section 307', true);
INSERT INTO Section (ActCode, SectionCode, SectionDescription, Active) VALUES ('IPC', '363', 'IPC Section 363', true);
INSERT INTO Section (ActCode, SectionCode, SectionDescription, Active) VALUES ('IPC', '364', 'IPC Section 364', true);
INSERT INTO Section (ActCode, SectionCode, SectionDescription, Active) VALUES ('IPC', '498A', 'IPC Section 498A', true);
INSERT INTO Section (ActCode, SectionCode, SectionDescription, Active) VALUES ('DVACT', '1', 'DVACT Section 1', true);
INSERT INTO Section (ActCode, SectionCode, SectionDescription, Active) VALUES ('POCSO', '4', 'POCSO Section 4', true);
INSERT INTO Section (ActCode, SectionCode, SectionDescription, Active) VALUES ('POCSO', '6', 'POCSO Section 6', true);
INSERT INTO Section (ActCode, SectionCode, SectionDescription, Active) VALUES ('IPC', '420', 'IPC Section 420', true);
INSERT INTO Section (ActCode, SectionCode, SectionDescription, Active) VALUES ('IPC', '406', 'IPC Section 406', true);
INSERT INTO Section (ActCode, SectionCode, SectionDescription, Active) VALUES ('IPC', '467', 'IPC Section 467', true);
INSERT INTO Section (ActCode, SectionCode, SectionDescription, Active) VALUES ('CUSTOMS', '135', 'CUSTOMS Section 135', true);
INSERT INTO Section (ActCode, SectionCode, SectionDescription, Active) VALUES ('IPC', '120B', 'IPC Section 120B', true);
INSERT INTO Section (ActCode, SectionCode, SectionDescription, Active) VALUES ('NDPS', '20', 'NDPS Section 20', true);
INSERT INTO Section (ActCode, SectionCode, SectionDescription, Active) VALUES ('NDPS', '21', 'NDPS Section 21', true);
INSERT INTO Section (ActCode, SectionCode, SectionDescription, Active) VALUES ('ITACT', '66C', 'ITACT Section 66C', true);
INSERT INTO Section (ActCode, SectionCode, SectionDescription, Active) VALUES ('ITACT', '66D', 'ITACT Section 66D', true);

INSERT INTO CrimeHeadActSection (CrimeHeadID, ActCode, SectionCode) VALUES (2, 'IPC', '356');
INSERT INTO CrimeHeadActSection (CrimeHeadID, ActCode, SectionCode) VALUES (1, 'IPC', '364');
INSERT INTO CrimeHeadActSection (CrimeHeadID, ActCode, SectionCode) VALUES (3, 'IPC', '498A');
INSERT INTO CrimeHeadActSection (CrimeHeadID, ActCode, SectionCode) VALUES (3, 'DVACT', '1');
INSERT INTO CrimeHeadActSection (CrimeHeadID, ActCode, SectionCode) VALUES (3, 'POCSO', '6');
INSERT INTO CrimeHeadActSection (CrimeHeadID, ActCode, SectionCode) VALUES (4, 'IPC', '120B');
INSERT INTO CrimeHeadActSection (CrimeHeadID, ActCode, SectionCode) VALUES (4, 'CUSTOMS', '135');
INSERT INTO CrimeHeadActSection (CrimeHeadID, ActCode, SectionCode) VALUES (5, 'NDPS', '21');
INSERT INTO CrimeHeadActSection (CrimeHeadID, ActCode, SectionCode) VALUES (6, 'ITACT', '66D');
