-- ═══════════════════════════════════════════════════════════════════════════
-- KSP CRIMINT — Catalyst Data Store Schema (v2.0 — Official ERD)
--
-- SOURCE OF TRUTH: Police_FIR_ER_Diagram.pdf, Karnataka Police Department
-- (Entity Relationship Diagram — Database Design Document, supplied by KSP
-- Hackathon organisers). This file implements that ERD exactly as specified —
-- table names, column names, types, and keys — in section 1 below.
--
-- Section 2 adds a small number of APPLICATION EXTENSION tables that are NOT
-- part of the supplied ERD. The ERD models FIR case records only; it has no
-- concept of app login/roles, audit trails, criminal network graphs, or
-- financial-crime linkage — all of which the hackathon problem statement
-- explicitly requires ("Criminal Network & Relationship Analysis",
-- "Financial Crime & Transaction Link Analysis", "Secure Role-Based Access").
-- Each extension table is called out with why it exists and is kept separate
-- from the ERD so the core FIR schema stays byte-for-byte faithful to spec.
--
-- KNOWN MODELLING LIMITATION (inherited from the ERD, not introduced here):
-- Accused rows are per-case (AccusedMasterID is scoped to one CaseMasterID;
-- PersonID is just a per-case display label like "A1"/"A2", not a stable
-- person identity). The ERD has no cross-case person entity, so "repeat
-- offender" analysis can only approximate identity by matching AccusedName —
-- see app-layer logic in data-query/chat-query for how this is handled.
--
-- Catalyst Data Store is MySQL-compatible. ROWID/CREATORID/CREATEDTIME/
-- MODIFIEDTIME are auto-generated by Catalyst — do NOT include them.
-- ═══════════════════════════════════════════════════════════════════════════


-- ═══════════════════════════════════════════════════════════════════════════
-- SECTION 1 — OFFICIAL ERD TABLES (Police FIR System)
-- ═══════════════════════════════════════════════════════════════════════════

-- ── Geography & jurisdiction ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS State (
  StateID       INT          NOT NULL,
  StateName     VARCHAR(100) NOT NULL,
  NationalityID INT,
  Active        BIT          DEFAULT 1,
  PRIMARY KEY (StateID)
);

CREATE TABLE IF NOT EXISTS District (
  DistrictID   INT          NOT NULL,
  DistrictName VARCHAR(100) NOT NULL,
  StateID      INT          NOT NULL,
  Active       BIT          DEFAULT 1,
  PRIMARY KEY (DistrictID),
  FOREIGN KEY (StateID) REFERENCES State (StateID)
);
CREATE INDEX idx_district_state ON District (StateID);

CREATE TABLE IF NOT EXISTS UnitType (
  UnitTypeID   INT         NOT NULL,
  UnitTypeName VARCHAR(80) NOT NULL,
  CityDistState VARCHAR(20),
  Hierarchy    INT,
  Active       BIT         DEFAULT 1,
  PRIMARY KEY (UnitTypeID)
);

CREATE TABLE IF NOT EXISTS Unit (
  UnitID        INT          NOT NULL,
  UnitName      VARCHAR(150) NOT NULL,
  TypeID        INT          NOT NULL,
  ParentUnit    INT,                          -- self-reference to UnitID
  NationalityID INT,
  StateID       INT          NOT NULL,
  DistrictID    INT          NOT NULL,
  Active        BIT          DEFAULT 1,
  PRIMARY KEY (UnitID),
  FOREIGN KEY (TypeID)     REFERENCES UnitType (UnitTypeID),
  FOREIGN KEY (StateID)    REFERENCES State (StateID),
  FOREIGN KEY (DistrictID) REFERENCES District (DistrictID),
  FOREIGN KEY (ParentUnit) REFERENCES Unit (UnitID)
);
CREATE INDEX idx_unit_district ON Unit (DistrictID);
CREATE INDEX idx_unit_state    ON Unit (StateID);

-- ── Personnel ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS Rank (
  RankID    INT         NOT NULL,
  RankName  VARCHAR(80) NOT NULL,
  Hierarchy INT,
  Active    BIT         DEFAULT 1,
  PRIMARY KEY (RankID)
);

CREATE TABLE IF NOT EXISTS Designation (
  DesignationID   INT         NOT NULL,
  DesignationName VARCHAR(100) NOT NULL,
  Active          BIT         DEFAULT 1,
  SortOrder       INT,
  PRIMARY KEY (DesignationID)
);

CREATE TABLE IF NOT EXISTS Employee (
  EmployeeID          INT          NOT NULL,
  DistrictID          INT          NOT NULL,
  UnitID              INT          NOT NULL,
  RankID              INT          NOT NULL,
  DesignationID       INT          NOT NULL,
  KGID                VARCHAR(30),
  FirstName           VARCHAR(100) NOT NULL,
  EmployeeDOB         DATE,
  GenderID            INT,
  BloodGroupID        INT,
  PhysicallyChallenged BIT         DEFAULT 0,
  AppointmentDate     DATE,
  PRIMARY KEY (EmployeeID),
  FOREIGN KEY (DistrictID)    REFERENCES District (DistrictID),
  FOREIGN KEY (UnitID)        REFERENCES Unit (UnitID),
  FOREIGN KEY (RankID)        REFERENCES Rank (RankID),
  FOREIGN KEY (DesignationID) REFERENCES Designation (DesignationID)
);
CREATE INDEX idx_employee_unit     ON Employee (UnitID);
CREATE INDEX idx_employee_district ON Employee (DistrictID);

CREATE TABLE IF NOT EXISTS Court (
  CourtID    INT          NOT NULL,
  CourtName  VARCHAR(150) NOT NULL,
  DistrictID INT          NOT NULL,
  StateID    INT          NOT NULL,
  Active     BIT          DEFAULT 1,
  PRIMARY KEY (CourtID),
  FOREIGN KEY (DistrictID) REFERENCES District (DistrictID),
  FOREIGN KEY (StateID)    REFERENCES State (StateID)
);

-- ── Case classification lookups ──────────────────────────────────────────
CREATE TABLE IF NOT EXISTS CaseCategory (
  CaseCategoryID INT         NOT NULL,
  LookupValue    VARCHAR(40) NOT NULL,      -- FIR, UDR, PAR, Zero FIR
  PRIMARY KEY (CaseCategoryID)
);

CREATE TABLE IF NOT EXISTS GravityOffence (
  GravityOffenceID INT         NOT NULL,
  LookupValue      VARCHAR(40) NOT NULL,    -- Heinous, Non-Heinous
  PRIMARY KEY (GravityOffenceID)
);

CREATE TABLE IF NOT EXISTS CaseStatusMaster (
  CaseStatusID   INT         NOT NULL,
  CaseStatusName VARCHAR(60) NOT NULL,      -- Under Investigation, Charge Sheeted, Closed...
  PRIMARY KEY (CaseStatusID)
);

CREATE TABLE IF NOT EXISTS CrimeHead (
  CrimeHeadID    INT          NOT NULL,
  CrimeGroupName VARCHAR(120) NOT NULL,     -- e.g. "Crimes Against Body"
  Active         BIT          DEFAULT 1,
  PRIMARY KEY (CrimeHeadID)
);

CREATE TABLE IF NOT EXISTS CrimeSubHead (
  CrimeSubHeadID INT          NOT NULL,
  CrimeHeadID    INT          NOT NULL,
  CrimeHeadName  VARCHAR(120) NOT NULL,     -- e.g. "Murder", "Robbery" (sub-head name, as per ERD)
  SeqID          INT,
  PRIMARY KEY (CrimeSubHeadID),
  FOREIGN KEY (CrimeHeadID) REFERENCES CrimeHead (CrimeHeadID)
);
CREATE INDEX idx_crimesubhead_head ON CrimeSubHead (CrimeHeadID);

-- ── Legal acts & sections ─────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS Act (
  ActCode        VARCHAR(20)  NOT NULL,     -- e.g. IPC, NDPS
  ActDescription VARCHAR(200) NOT NULL,
  ShortName      VARCHAR(40),
  Active         BIT          DEFAULT 1,
  PRIMARY KEY (ActCode)
);

CREATE TABLE IF NOT EXISTS Section (
  ActCode            VARCHAR(20) NOT NULL,
  SectionCode        VARCHAR(20) NOT NULL,   -- e.g. 302, 307
  SectionDescription VARCHAR(200),
  Active             BIT DEFAULT 1,
  PRIMARY KEY (ActCode, SectionCode),
  FOREIGN KEY (ActCode) REFERENCES Act (ActCode)
);

CREATE TABLE IF NOT EXISTS CrimeHeadActSection (
  CrimeHeadID INT         NOT NULL,
  ActCode     VARCHAR(20) NOT NULL,
  SectionCode VARCHAR(20),
  PRIMARY KEY (CrimeHeadID, ActCode),
  FOREIGN KEY (CrimeHeadID) REFERENCES CrimeHead (CrimeHeadID),
  FOREIGN KEY (ActCode)     REFERENCES Act (ActCode)
);

-- ── Complainant demographic lookups ──────────────────────────────────────
CREATE TABLE IF NOT EXISTS CasteMaster (
  caste_master_id   INT         NOT NULL,
  caste_master_name VARCHAR(80) NOT NULL,
  PRIMARY KEY (caste_master_id)
);

CREATE TABLE IF NOT EXISTS ReligionMaster (
  ReligionID   INT         NOT NULL,
  ReligionName VARCHAR(60) NOT NULL,
  PRIMARY KEY (ReligionID)
);

CREATE TABLE IF NOT EXISTS OccupationMaster (
  OccupationID   INT         NOT NULL,
  OccupationName VARCHAR(80) NOT NULL,
  PRIMARY KEY (OccupationID)
);

-- ── Core case record ──────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS CaseMaster (
  CaseMasterID        INT          NOT NULL,
  CrimeNo             VARCHAR(30)  NOT NULL,   -- 1+4+4+4+5 digit structured code — see ERD doc
  CaseNo              VARCHAR(20)  NOT NULL,   -- YYYY + 5-digit serial (last 9 digits of CrimeNo)
  CrimeRegisteredDate DATE         NOT NULL,
  PolicePersonID      INT          NOT NULL,
  PoliceStationID     INT          NOT NULL,
  CaseCategoryID      INT          NOT NULL,
  GravityOffenceID    INT          NOT NULL,
  CrimeMajorHeadID    INT          NOT NULL,
  CrimeMinorHeadID    INT          NOT NULL,
  CaseStatusID        INT          NOT NULL,
  CourtID             INT,
  PRIMARY KEY (CaseMasterID),
  FOREIGN KEY (PolicePersonID)   REFERENCES Employee (EmployeeID),
  FOREIGN KEY (PoliceStationID)  REFERENCES Unit (UnitID),
  FOREIGN KEY (CaseCategoryID)   REFERENCES CaseCategory (CaseCategoryID),
  FOREIGN KEY (GravityOffenceID) REFERENCES GravityOffence (GravityOffenceID),
  FOREIGN KEY (CrimeMajorHeadID) REFERENCES CrimeHead (CrimeHeadID),
  FOREIGN KEY (CrimeMinorHeadID) REFERENCES CrimeSubHead (CrimeSubHeadID),
  FOREIGN KEY (CaseStatusID)     REFERENCES CaseStatusMaster (CaseStatusID),
  FOREIGN KEY (CourtID)          REFERENCES Court (CourtID)
);
CREATE INDEX idx_casemaster_station  ON CaseMaster (PoliceStationID);
CREATE INDEX idx_casemaster_status   ON CaseMaster (CaseStatusID);
CREATE INDEX idx_casemaster_majorhead ON CaseMaster (CrimeMajorHeadID);
CREATE INDEX idx_casemaster_minorhead ON CaseMaster (CrimeMinorHeadID);
CREATE INDEX idx_casemaster_date     ON CaseMaster (CrimeRegisteredDate);

-- One-to-one with CaseMaster per the ERD's Relationship Matrix (occurrence
-- time/location kept out of CaseMaster proper).
CREATE TABLE IF NOT EXISTS Inv_OccuranceTime (
  CaseMasterID    INT           NOT NULL,
  IncidentFromDate DATETIME,
  IncidentToDate   DATETIME,
  InfoReceivedPSDate DATETIME,
  latitude        DECIMAL(10,6),
  longitude       DECIMAL(10,6),
  BriefFacts      TEXT,
  PRIMARY KEY (CaseMasterID),
  FOREIGN KEY (CaseMasterID) REFERENCES CaseMaster (CaseMasterID)
);
CREATE INDEX idx_occtime_geo ON Inv_OccuranceTime (latitude, longitude);

CREATE TABLE IF NOT EXISTS ComplainantDetails (
  ComplainantID   INT          NOT NULL,
  CaseMasterID    INT          NOT NULL,
  ComplainantName VARCHAR(150) NOT NULL,
  AgeYear         INT,
  OccupationID    INT,
  ReligionID      INT,
  CasteID         INT,
  GenderID        INT,
  PRIMARY KEY (ComplainantID),
  FOREIGN KEY (CaseMasterID) REFERENCES CaseMaster (CaseMasterID),
  FOREIGN KEY (OccupationID) REFERENCES OccupationMaster (OccupationID),
  FOREIGN KEY (ReligionID)   REFERENCES ReligionMaster (ReligionID),
  FOREIGN KEY (CasteID)      REFERENCES CasteMaster (caste_master_id)
);
CREATE INDEX idx_complainant_case ON ComplainantDetails (CaseMasterID);

CREATE TABLE IF NOT EXISTS ActSectionAssociation (
  CaseMasterID   INT         NOT NULL,
  ActID          VARCHAR(20) NOT NULL,      -- FK -> Act.ActCode
  SectionID      VARCHAR(20) NOT NULL,      -- FK -> Section.SectionCode
  ActOrderID     INT,
  SectionOrderID INT,
  PRIMARY KEY (CaseMasterID, ActID, SectionID),
  FOREIGN KEY (CaseMasterID) REFERENCES CaseMaster (CaseMasterID),
  FOREIGN KEY (ActID)        REFERENCES Act (ActCode)
);
CREATE INDEX idx_actsection_case ON ActSectionAssociation (CaseMasterID);

CREATE TABLE IF NOT EXISTS Victim (
  VictimMasterID INT          NOT NULL,
  CaseMasterID   INT          NOT NULL,
  VictimName     VARCHAR(150) NOT NULL,
  AgeYear        INT,
  GenderID       INT,                        -- m, f, t
  VictimPolice   VARCHAR(1)   DEFAULT '0',    -- '1' if victim is police, else '0'
  PRIMARY KEY (VictimMasterID),
  FOREIGN KEY (CaseMasterID) REFERENCES CaseMaster (CaseMasterID)
);
CREATE INDEX idx_victim_case ON Victim (CaseMasterID);

CREATE TABLE IF NOT EXISTS Accused (
  AccusedMasterID INT          NOT NULL,
  CaseMasterID    INT          NOT NULL,
  AccusedName     VARCHAR(150) NOT NULL,
  AgeYear         INT,
  GenderID        VARCHAR(1),                -- M/F/T per ERD
  PersonID        VARCHAR(10),               -- per-case display label: A1, A2, A3...
  PRIMARY KEY (AccusedMasterID),
  FOREIGN KEY (CaseMasterID) REFERENCES CaseMaster (CaseMasterID)
);
CREATE INDEX idx_accused_case ON Accused (CaseMasterID);
CREATE INDEX idx_accused_name ON Accused (AccusedName);

CREATE TABLE IF NOT EXISTS ArrestSurrender (
  ArrestSurrenderID         INT  NOT NULL,
  CaseMasterID              INT  NOT NULL,
  ArrestSurrenderTypeID     INT,             -- lookup: arrest | voluntary surrender
  ArrestSurrenderDate       DATE,
  ArrestSurrenderStateId    INT,
  ArrestSurrenderDistrictId INT,
  PoliceStationID           INT,
  IOID                      INT,
  CourtID                   INT,
  AccusedMasterID           INT,
  IsAccused                 BIT DEFAULT 0,
  IsComplainantAccused      BIT DEFAULT 0,
  PRIMARY KEY (ArrestSurrenderID),
  FOREIGN KEY (CaseMasterID)              REFERENCES CaseMaster (CaseMasterID),
  FOREIGN KEY (ArrestSurrenderStateId)    REFERENCES State (StateID),
  FOREIGN KEY (ArrestSurrenderDistrictId) REFERENCES District (DistrictID),
  FOREIGN KEY (PoliceStationID)           REFERENCES Unit (UnitID),
  FOREIGN KEY (IOID)                      REFERENCES Employee (EmployeeID),
  FOREIGN KEY (CourtID)                   REFERENCES Court (CourtID),
  FOREIGN KEY (AccusedMasterID)           REFERENCES Accused (AccusedMasterID)
);
CREATE INDEX idx_arrestsurrender_case ON ArrestSurrender (CaseMasterID);
CREATE INDEX idx_arrestsurrender_accused ON ArrestSurrender (AccusedMasterID);

-- Junction table per the ERD's Relationship Matrix: one arrest/surrender
-- event can link multiple accused. (Note: ArrestSurrender also carries a
-- direct AccusedMasterID column above — both are kept exactly as specified
-- in the source ERD, which documents this junction independently.)
CREATE TABLE IF NOT EXISTS inv_arrestsurrenderaccused (
  ArrestSurrenderID INT NOT NULL,
  AccusedMasterID   INT NOT NULL,
  PRIMARY KEY (ArrestSurrenderID, AccusedMasterID),
  FOREIGN KEY (ArrestSurrenderID) REFERENCES ArrestSurrender (ArrestSurrenderID),
  FOREIGN KEY (AccusedMasterID)   REFERENCES Accused (AccusedMasterID)
);

CREATE TABLE IF NOT EXISTS ChargesheetDetails (
  CSID           INT      NOT NULL,
  CaseMasterID   INT      NOT NULL,
  csdate         DATETIME,
  cstype         CHAR(1),                   -- A=Chargesheet, B=False Case, C=Undetected
  PolicePersonID INT,
  PRIMARY KEY (CSID),
  FOREIGN KEY (CaseMasterID)   REFERENCES CaseMaster (CaseMasterID),
  FOREIGN KEY (PolicePersonID) REFERENCES Employee (EmployeeID)
);
CREATE INDEX idx_chargesheet_case ON ChargesheetDetails (CaseMasterID);


-- ═══════════════════════════════════════════════════════════════════════════
-- SECTION 2 — APPLICATION EXTENSION TABLES (not part of the supplied ERD)
-- Each exists to satisfy an explicit hackathon capability the base FIR
-- registry does not model. Kept separate from Section 1 by design.
-- ═══════════════════════════════════════════════════════════════════════════

-- Extension reason: app login + role-based access control (Module 13 /
-- "Secure Role-Based Access & Governance"). The ERD's Employee table has no
-- concept of an application role or login credential.
CREATE TABLE IF NOT EXISTS UserProfiles (
  user_id      VARCHAR(50)  NOT NULL,
  email        VARCHAR(100) NOT NULL,
  first_name   VARCHAR(50)  NOT NULL,
  last_name    VARCHAR(50)  NOT NULL,
  role         VARCHAR(30)  NOT NULL,   -- admin|supervisor|investigator|analyst|policymaker
  EmployeeID   INT,                     -- optional link to Employee if the user is a serving officer
  is_active    TINYINT(1)   DEFAULT 1,
  created_at   DATETIME     DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id),
  FOREIGN KEY (EmployeeID) REFERENCES Employee (EmployeeID)
);

-- Extension reason: audit trail / accountability (Module 13). No table in
-- the ERD records who queried or exported what.
CREATE TABLE IF NOT EXISTS AuditLogs (
  log_id        VARCHAR(30) NOT NULL,
  user_id       VARCHAR(50),
  action        VARCHAR(80),
  resource_type VARCHAR(40),
  resource_id   VARCHAR(40),
  query_text    TEXT,
  ip_address    VARCHAR(45),
  created_at    DATETIME    DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (log_id),
  FOREIGN KEY (user_id) REFERENCES UserProfiles (user_id)
);

-- Extension reason: "Criminal Network & Relationship Analysis" is an
-- explicit required capability, but the ERD has no graph/edge concept
-- linking accused, victims, locations, or accounts across cases.
CREATE TABLE IF NOT EXISTS Relationships (
  rel_id    VARCHAR(20) NOT NULL,
  from_id   VARCHAR(20) NOT NULL,       -- e.g. AccusedMasterID, VictimMasterID
  from_type VARCHAR(20),                -- Accused|Victim|Employee|Account
  to_id     VARCHAR(20) NOT NULL,
  to_type   VARCHAR(20),
  rel_type  VARCHAR(60),                -- Co-offender|Gang Member|Associate|Financial Link
  strength  DECIMAL(4,2),               -- 0.0–1.0 confidence
  CaseMasterID INT,                     -- evidencing case, if any
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (rel_id),
  FOREIGN KEY (CaseMasterID) REFERENCES CaseMaster (CaseMasterID)
);
CREATE INDEX idx_rel_from ON Relationships (from_id, from_type);
CREATE INDEX idx_rel_to   ON Relationships (to_id, to_type);

-- Extension reason: "Financial Crime & Transaction Link Analysis" is an
-- explicit required capability; the ERD has no financial-account concept.
CREATE TABLE IF NOT EXISTS FinancialAccounts (
  account_id              VARCHAR(20)  NOT NULL,
  account_number          VARCHAR(50),
  bank                    VARCHAR(80),
  linked_accused_id       INT,                    -- FK -> Accused.AccusedMasterID
  flagged                 TINYINT(1)   DEFAULT 0,
  suspicious_txn_count    INT          DEFAULT 0,
  total_suspicious_amount BIGINT       DEFAULT 0,
  notes                   TEXT,
  created_at              DATETIME     DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (account_id),
  FOREIGN KEY (linked_accused_id) REFERENCES Accused (AccusedMasterID)
);
CREATE INDEX idx_finacc_accused ON FinancialAccounts (linked_accused_id);
CREATE INDEX idx_finacc_flagged ON FinancialAccounts (flagged);

-- ═══════════════════════════════════════════════════════════════════════════
-- SECTION 3 — CHAT & BRIEFING HISTORY (persisted server-side, not localStorage)
-- Every officer's chat conversations and generated intelligence briefings are
-- stored here so they survive across devices/sessions and can be revisited
-- or deleted — matching how consumer AI assistants persist conversation
-- history server-side rather than only in browser storage.
-- ═══════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS ChatSessions (
  session_id     VARCHAR(40)  NOT NULL,
  user_id        VARCHAR(50)  NOT NULL,
  title          VARCHAR(200),          -- RAG-rephrased short title from the first question
  message_count  INT          DEFAULT 0,
  created_at     DATETIME     DEFAULT CURRENT_TIMESTAMP,
  updated_at     DATETIME     DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (session_id),
  FOREIGN KEY (user_id) REFERENCES UserProfiles (user_id)
);
CREATE INDEX idx_chatsess_user ON ChatSessions (user_id, updated_at);

CREATE TABLE IF NOT EXISTS ChatMessages (
  message_id   VARCHAR(40) NOT NULL,
  session_id   VARCHAR(40) NOT NULL,
  sender       VARCHAR(10) NOT NULL,    -- user|ai
  text         TEXT,
  intent       VARCHAR(40),
  confidence   INT,
  reasoning    TEXT,                    -- JSON-encoded string[]
  highlights   TEXT,                    -- JSON-encoded array
  suggestions  TEXT,                    -- JSON-encoded string[]
  action       TEXT,                    -- JSON-encoded object|null
  alert        TEXT,
  evidence     TEXT,                    -- JSON-encoded string[]
  created_at   DATETIME    DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (message_id),
  FOREIGN KEY (session_id) REFERENCES ChatSessions (session_id)
);
CREATE INDEX idx_chatmsg_session ON ChatMessages (session_id, created_at);

CREATE TABLE IF NOT EXISTS Briefings (
  briefing_id   VARCHAR(40) NOT NULL,
  user_id       VARCHAR(50) NOT NULL,
  scope         VARCHAR(100),
  generated_by  VARCHAR(20),            -- rag|template
  confidence    INT,
  briefing_text TEXT,
  stats         TEXT,                   -- JSON-encoded snapshot
  created_at    DATETIME    DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (briefing_id),
  FOREIGN KEY (user_id) REFERENCES UserProfiles (user_id)
);
CREATE INDEX idx_briefing_user ON Briefings (user_id, created_at);

-- Extension reason: the ERD has no photograph/image concept for Accused at
-- all. Real photos aren't available in this dataset, so the UI shows a
-- default silhouette poster and lets an officer attach one manually — stored
-- as a resized/compressed base64 JPEG data URI.
--
-- CHUNKED BY DESIGN: Catalyst's Data Store silently truncates any TEXT
-- column value to exactly 10,000 characters (confirmed empirically — not
-- documented) rather than erroring, which corrupted every photo above ~7KB
-- raw into an unparseable data URI. A single ~15-40KB compressed thumbnail
-- doesn't fit in one TEXT cell, so it's split into <=8000-char chunks across
-- multiple rows here and reassembled by chunk_index on read.
CREATE TABLE IF NOT EXISTS AccusedPhotoChunks (
  chunk_id     VARCHAR(40) NOT NULL,   -- '<accused_id>-<chunk_index>', e.g. 'ACC-123-0'
  accused_id   VARCHAR(20) NOT NULL,   -- e.g. 'ACC-123' — the app's display ID
  chunk_index  INT         NOT NULL,
  chunk_data   TEXT,                   -- <=8000 chars of the base64 data URI, well under the 10,000 cap
  uploaded_by  VARCHAR(50),
  uploaded_at  DATETIME    DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (chunk_id)
);
CREATE INDEX idx_photochunk_accused ON AccusedPhotoChunks (accused_id, chunk_index);
